In [2]:
import pandas as pd
import matplotlib.pyplot as plt
iris=pd.read_csv("iris.csv")

In [3]:
print(iris.head(5))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [9]:
l=iris["species"]
iris_d=iris.drop("species",axis=1)

In [10]:
print(iris_d.shape)
print(l.shape)

(150, 4)
(150,)


In [12]:
print(iris_d.head(5))

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2


In [13]:
# Data-preprocessing: Standardizing the data

from sklearn.preprocessing import StandardScaler
standardized_data = StandardScaler().fit_transform(iris_d)
print(standardized_data.shape)


(150, 4)


In [16]:
print(standardized_data)

[[-9.00681170e-01  1.03205722e+00 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00 -1.24957601e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.38535265e+00  3.37848329e-01 -1.39813811e+00 -1.31297673e+00]
 [-1.50652052e+00  1.06445364e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.02184904e+00  1.26346019e+00 -1.34127240e+00 -1.31297673e+00]
 [-5.37177559e-01  1.95766909e+00 -1.17067529e+00 -1.05003079e+00]
 [-1.50652052e+00  8.00654259e-01 -1.34127240e+00 -1.18150376e+00]
 [-1.02184904e+00  8.00654259e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.74885626e+00 -3.56360566e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00  1.06445364e-01 -1.28440670e+00 -1.44444970e+00]
 [-5.37177559e-01  1.49486315e+00 -1.28440670e+00 -1.31297673e+00]
 [-1.26418478e+00  8.00654259e-01 -1.22754100e+00 -1.31297673e+00]
 [-1.26418478e+00 -1.24957601e-01 -1.34127240e+00 -1.44444970e+00]
 [-1.87002413e+00 -1.24957601e-01 -1.51186952e+00 -1.44444970e+00]
 [-5.25060772e-02  2.18907205e+00 -1.45500381e+00 -1.31297673e

In [14]:
import numpy as np
sample_data=standardized_data
covar_matrix=np.matmul(sample_data.T,sample_data)
print(covar_matrix.shape)


(4, 4)


In [18]:
from scipy.linalg import eigh
values,vectors=eigh(covar_matrix,eigvals=(2,3))
print(vectors.shape)


(4, 2)


C:\Users\DELL\AppData\Local\Temp\ipykernel_16088\1568435957.py:2: DeprecationWarning: Keyword argument 'eigvals' is deprecated in favour of 'subset_by_index' keyword instead and will be removed in SciPy 1.12.0.
  values,vectors=eigh(covar_matrix,eigvals=(2,3))


In [1]:
vectors=vectors.T
new_coordinates=np.matmul(vectors,sample_data.T)
new_coordinates=np.
dataframe=pd.DataFrame(data=new_coordinates,colums=("1st_principal","2nd_principal","specied"))
print(dataframe.head())

SyntaxError: invalid syntax (3975960260.py, line 3)